import { z } from 'zod';
import { eq, and, desc } from 'drizzle-orm';
import { db, financialNotes, accounts, organisations } from '../db/schema';
import { AppError } from '../lib/errors';
import { getBalanceSheet, getProfitAndLoss, getCashFlowStatement, getStatementOfChangesInEquity, getTrialBalance } from './ledger.service';

export const noteSchema = z.object({
  noteNumber: z.string(),
  title: z.string(),
  content: z.string().optional(),
  autoGenerated: z.boolean().default(true),
  sourceReport: z.string().optional(),
  noteData: z.any().optional(),
  sortOrder: z.number().int().default(0),
});

export interface FinancialNote {
  id: string;
  orgId: string;
  noteNumber: string;
  title: string;
  content: string | null;
  autoGenerated: boolean;
  sourceReport: string | null;
  reportDate: Date | null;
  noteData: any;
  sortOrder: number;
}

export async function getNotes(orgId: string, sourceReport?: string): Promise<FinancialNote[]> {
  const conditions = [eq(financialNotes.orgId, orgId)];
  if (sourceReport) conditions.push(eq(financialNotes.sourceReport, sourceReport));

  const rows = await db
    .select()
    .from(financialNotes)
    .where(and(...conditions))
    .orderBy(financialNotes.sortOrder);

  return rows.map(r => ({
    id: r.id,
    orgId: r.orgId,
    noteNumber: r.noteNumber,
    title: r.title,
    content: r.content,
    autoGenerated: r.autoGenerated,
    sourceReport: r.sourceReport,
    reportDate: r.reportDate,
    noteData: r.noteData,
    sortOrder: r.sortOrder,
  }));
}

export async function saveNote(
  orgId: string,
  userId: string,
  data: z.infer<typeof noteSchema>,
  noteId?: string
): Promise<FinancialNote> {
  if (noteId) {
    const existing = await db
      .select()
      .from(financialNotes)
      .where(and(eq(financialNotes.id, noteId), eq(financialNotes.orgId, orgId)))
      .limit(1);

    if (existing.length === 0) throw new AppError('Note not found', 404);

    await db
      .update(financialNotes)
      .set({
        title: data.title,
        content: data.content,
        autoGenerated: data.autoGenerated,
        sourceReport: data.sourceReport,
        noteData: data.noteData,
        sortOrder: data.sortOrder,
        updatedBy: userId,
        updatedAt: new Date(),
      })
      .where(eq(financialNotes.id, noteId));

    const notes = await getNotes(orgId);
    return notes.find(n => n.id === noteId)!;
  }

  await db.insert(financialNotes).values({
    orgId,
    noteNumber: data.noteNumber,
    title: data.title,
    content: data.content || null,
    autoGenerated: data.autoGenerated,
    sourceReport: data.sourceReport || null,
    noteData: data.noteData || null,
    sortOrder: data.sortOrder,
    createdBy: userId,
    updatedBy: userId,
    reportDate: new Date(),
  });

  const notes = await getNotes(orgId);
  return notes.find(n => n.noteNumber === data.noteNumber && n.title === data.title)!;
}

export async function deleteNote(orgId: string, noteId: string): Promise<void> {
  const existing = await db
    .select()
    .from(financialNotes)
    .where(and(eq(financialNotes.id, noteId), eq(financialNotes.orgId, orgId)))
    .limit(1);

  if (existing.length === 0) throw new AppError('Note not found', 404);

  await db.delete(financialNotes).where(eq(financialNotes.id, noteId));
}

export async function generateDefaultNotes(
  orgId: string,
  reportDate: Date,
  userId: string
): Promise<FinancialNote[]> {
  const existing = await getNotes(orgId);
  if (existing.length > 0) return existing; // don't regenerate if notes exist

  const [org] = await db
    .select({ name: organisations.name })
    .from(organisations)
    .where(eq(organisations.id, orgId))
    .limit(1);

  const orgName = org?.name || 'The Organisation';
  const fyEnd = reportDate.toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
  const fyStart = new Date(reportDate.getFullYear(), 0, 1).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });

  // Fetch financial data for auto-populated notes
  const [bs, pnl, cf, socie, tb] = await Promise.all([
    getBalanceSheet(orgId, reportDate).catch(() => null),
    getProfitAndLoss(orgId, new Date(reportDate.getFullYear(), 0, 1), reportDate).catch(() => null),
    getCashFlowStatement(orgId, new Date(reportDate.getFullYear(), 0, 1), reportDate).catch(() => null),
    getStatementOfChangesInEquity(orgId, reportDate).catch(() => ({ currentYear: null, priorYear: null })),
    getTrialBalance(orgId, new Date('2000-01-01'), reportDate).catch(() => null),
  ]);

  const assets: any[] = []; // would query fixedAssets if needed

  const netProfit = pnl?.current?.netProfit || 0;
  const totalAssets = bs?.totalAssets || 0;
  const totalLiabilities = bs?.totalLiabilities || 0;
  const totalEquity = bs?.totalEquity || 0;

  const defaultNotes = [
    {
      noteNumber: '1',
      title: 'Corporate Information and Nature of Operations',
      content: `${orgName} is a private limited liability company incorporated in Nigeria. The principal activities of the company include providing financial and business services. The financial statements for the year ended ${fyEnd} were approved by the Board of Directors on ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric'})}.`,
      autoGenerated: true,
      sourceReport: 'annual_report',
      sortOrder: 1,
    },
    {
      noteNumber: '2',
      title: 'Statement of Compliance and Basis of Preparation',
      content: `The financial statements have been prepared in accordance with International Financial Reporting Standards (IFRS) as issued by the International Accounting Standards Board (IASB). The financial statements are prepared under the historical cost convention, except for certain financial instruments which are measured at fair value. The presentation currency is Nigerian Naira (NGN).`,
      autoGenerated: true,
      sourceReport: 'annual_report',
      sortOrder: 2,
    },
    {
      noteNumber: '3',
      title: 'Summary of Significant Accounting Policies',
      content: `The principal accounting policies adopted in the preparation of these financial statements are set out below:\n\n` +
        `**Revenue Recognition:** Revenue is recognised when control of goods or services is transferred to the customer at an amount that reflects the consideration to which the company expects to be entitled.\n\n` +
        `**Property, Plant and Equipment:** Property, plant and equipment are stated at cost less accumulated depreciation and impairment losses. Depreciation is charged on a straight-line basis over the estimated useful lives of the assets.\n\n` +
        `**Financial Instruments:** Financial assets and financial liabilities are recognised when the company becomes a party to the contractual provisions of the instrument.\n\n` +
        `** Taxation:** Income tax expense comprises current and deferred tax. Current tax is calculated based on taxable profit for the year using tax rates enacted at the reporting date.\n\n` +
        `**Foreign Currency Translation:** Transactions in foreign currencies are translated at the exchange rate at the date of the transaction. Monetary assets and liabilities denominated in foreign currencies are translated at the closing rate at the reporting date.`,
      autoGenerated: true,
      sourceReport: 'annual_report',
      sortOrder: 3,
    },
    {
      noteNumber: '4',
      title: 'Profit for the Year',
      content: `The profit for the year ended ${fyEnd} is NGN ${(netProfit / 100).toLocaleString('en-NG', { minimumFractionDigits: 2 })} (${fyStart} - ${fyEnd}). This is after charging all operating expenses, finance costs, and income tax.`,
      autoGenerated: true,
      sourceReport: 'income_statement',
      sortOrder: 4,
      noteData: { netProfit },
    },
    {
      noteNumber: '5',
      title: 'Property, Plant and Equipment',
      content: assets && assets.length > 0
        ? `The company's property, plant and equipment as at ${fyEnd} comprise the following classes. Details of movements during the year are provided in the fixed assets schedule.`
        : 'The company had no material property, plant and equipment as at the reporting date.',
      autoGenerated: true,
      sourceReport: 'balance_sheet',
      sortOrder: 5,
      noteData: assets || [],
    },
    {
      noteNumber: '6',
      title: 'Trade and Other Receivables',
      content: `Trade and other receivables as at ${fyEnd} total NGN ${(totalAssets / 100).toLocaleString('en-NG', { minimumFractionDigits: 2 })}. These are stated at their invoice amounts less appropriate allowances for estimated irrecoverable amounts.`,
      autoGenerated: true,
      sourceReport: 'balance_sheet',
      sortOrder: 6,
      noteData: { totalReceivables: totalAssets },
    },
    {
      noteNumber: '7',
      title: 'Cash and Cash Equivalents',
      content: `Cash and cash equivalents include cash on hand, bank balances, and short-term deposits with original maturities of three months or less. As at ${fyEnd}, the balance comprises bank accounts and cash holdings as detailed in the statement of cash flows.`,
      autoGenerated: true,
      sourceReport: 'cash_flow',
      sortOrder: 7,
      noteData: cf?.closingCash ? { closingCash: cf.closingCash } : {},
    },
    {
      noteNumber: '8',
      title: 'Trade and Other Payables',
      content: `Trade and other payables as at ${fyEnd} total NGN ${(totalLiabilities / 100).toLocaleString('en-NG', { minimumFractionDigits: 2 })}. These are non-interest bearing and are settled within normal commercial terms.`,
      autoGenerated: true,
      sourceReport: 'balance_sheet',
      sortOrder: 8,
      noteData: { totalLiabilities },
    },
    {
      noteNumber: '9',
      title: 'Share Capital and Reserves',
      content: socie && socie.currentYear?.columns
        ? `Share capital and reserves as at ${fyEnd} total NGN ${(totalEquity / 100).toLocaleString('en-NG', { minimumFractionDigits: 2 })}. Details of movements in each component of equity are presented in the Statement of Changes in Equity.`
        : 'The company\'s equity structure comprises share capital and retained earnings as detailed in the Statement of Changes in Equity.',
      autoGenerated: true,
      sourceReport: 'balance_sheet',
      sortOrder: 9,
      noteData: socie?.currentYear || {},
    },
    {
      noteNumber: '10',
      title: 'Events After the Reporting Period',
      content: 'There were no material events after the reporting period that require adjustment to or disclosure in these financial statements.',
      autoGenerated: true,
      sourceReport: 'annual_report',
      sortOrder: 10,
    },
    {
      noteNumber: '11',
      title: 'Going Concern',
      content: `The financial statements have been prepared on a going concern basis. The directors have assessed the company's ability to continue as a going concern and have concluded that there are no material uncertainties that may cast significant doubt on the company's ability to continue as a going concern.`,
      autoGenerated: true,
      sourceReport: 'annual_report',
      sortOrder: 11,
    },
    {
      noteNumber: '12',
      title: 'Contingent Liabilities and Commitments',
      content: 'There were no significant contingent liabilities or capital commitments as at the reporting date.',
      autoGenerated: true,
      sourceReport: 'annual_report',
      sortOrder: 12,
    },
    {
      noteNumber: '13',
      title: 'Related Party Transactions',
      content: 'All transactions with related parties were conducted at arm\'s length on normal commercial terms. Details of significant related party transactions are disclosed where applicable.',
      autoGenerated: true,
      sourceReport: 'annual_report',
      sortOrder: 13,
    },
    {
      noteNumber: '14',
      title: 'Financial Risk Management',
      content: `The company is exposed to credit risk, liquidity risk, and market risk. The board of directors oversees the management of these risks. The company's overall risk management programme focuses on the unpredictability of financial markets and seeks to minimise potential adverse effects on the company's financial performance.`,
      autoGenerated: true,
      sourceReport: 'annual_report',
      sortOrder: 14,
    },
    {
      noteNumber: '15',
      title: 'Taxation',
      content: pnl?.current
        ? `Income tax expense for the year ended ${fyEnd} is calculated based on the applicable tax rates in Nigeria. The charge for the year comprises current tax and deferred tax.`
        : 'No income tax expense was recognised in the period.',
      autoGenerated: true,
      sourceReport: 'income_statement',
      sortOrder: 15,
    },
  ];

  for (const note of defaultNotes) {
    await db.insert(financialNotes).values({
      orgId,
      noteNumber: note.noteNumber,
      title: note.title,
      content: note.content,
      autoGenerated: note.autoGenerated,
      sourceReport: note.sourceReport,
      noteData: note.noteData || null,
      sortOrder: note.sortOrder,
      createdBy: userId,
      updatedBy: userId,
      reportDate,
    });
  }

  return getNotes(orgId);
}

export async function regenerateNotes(
  orgId: string,
  reportDate: Date,
  userId: string
): Promise<FinancialNote[]> {
  // Delete existing auto-generated notes
  await db
    .delete(financialNotes)
    .where(
      and(
        eq(financialNotes.orgId, orgId),
        eq(financialNotes.autoGenerated, true)
      )
    );

  return generateDefaultNotes(orgId, reportDate, userId);
}
