import { db, accounts } from './schema';
import { eq } from 'drizzle-orm';

const ACCOUNT_SEEDS: { code: string; name: string; type: 'asset' | 'liability' | 'equity' | 'revenue' | 'expense'; subType: string | null; description: string | null }[] = [
  // ── CURRENT ASSETS ──
  { code: '100000', name: 'Cash and Cash Equivalents', type: 'asset', subType: 'Current Assets', description: 'IAS 7 – Cash, petty cash, bank balances. CBN regulated — naira & domiciliary accounts.' },
  { code: '100100', name: 'Cash on Hand', type: 'asset', subType: 'Current Assets', description: 'IAS 7 – Physical naira notes and coins. Includes foreign currency cash.' },
  { code: '100200', name: 'Cash at Bank – Naira', type: 'asset', subType: 'Current Assets', description: 'IAS 7 – CBN-regulated commercial bank accounts. Specify bank name in sub-ledger.' },
  { code: '100300', name: 'Cash at Bank – Foreign Currency', type: 'asset', subType: 'Current Assets', description: 'IAS 7 / IAS 21 – USD, EUR, GBP domiciliary accounts. Retranslate at closing rate.' },
  { code: '100400', name: 'Petty Cash', type: 'asset', subType: 'Current Assets', description: 'IAS 7 – Imprest system petty cash fund.' },
  { code: '100500', name: 'Short-term Bank Deposits (<3 months)', type: 'asset', subType: 'Current Assets', description: 'IAS 7 – Treasury bills, fixed deposits ≤ 90 days. WHT deducted at source.' },
  { code: '101000', name: 'Trade & Other Receivables', type: 'asset', subType: 'Current Assets', description: 'IFRS 9 / IAS 32 – Amounts due from customers. Expected Credit Loss (ECL) model applies.' },
  { code: '101100', name: 'Trade Receivables', type: 'asset', subType: 'Current Assets', description: 'IFRS 15 / IFRS 9 – Invoiced revenue not yet collected. Stage 1–3 impairment per IFRS 9.' },
  { code: '101200', name: 'Allowance for Impairment (contra)', type: 'asset', subType: 'Current Assets', description: 'IFRS 9 – ECL provision against trade receivables. 12-month or lifetime ECL.' },
  { code: '101300', name: 'Staff Advances & Loans', type: 'asset', subType: 'Current Assets', description: 'IAS 19 / IFRS 9 – Advances to employees. PAYE implications on benefit element.' },
  { code: '101400', name: 'Receivable from Related Parties', type: 'asset', subType: 'Current Assets', description: 'IAS 24 – Amounts due from subsidiaries / associates. Transfer pricing rules apply.' },
  { code: '101500', name: 'WHT Receivable', type: 'asset', subType: 'Current Assets', description: 'CITA / WHT Regs – Withholding tax credit receivable. Obtain WHT credit notes from FIRS.' },
  { code: '101600', name: 'VAT Receivable / Input VAT', type: 'asset', subType: 'Current Assets', description: 'VATA – Input VAT recoverable from FIRS. File VAT returns monthly; offset against output VAT.' },
  { code: '101700', name: 'Prepayments', type: 'asset', subType: 'Current Assets', description: 'IAS 1 – Expenses paid in advance (rents, insurance, subscriptions).' },
  { code: '101800', name: 'Other Receivables', type: 'asset', subType: 'Current Assets', description: 'IFRS 9 – Deposits, claims receivable.' },
  { code: '102000', name: 'Inventories', type: 'asset', subType: 'Current Assets', description: 'IAS 2 – Goods held for sale or production.' },
  { code: '102100', name: 'Raw Materials', type: 'asset', subType: 'Current Assets', description: 'IAS 2 – Materials for manufacturing.' },
  { code: '102200', name: 'Work-in-Progress', type: 'asset', subType: 'Current Assets', description: 'IAS 2 – Partially completed goods.' },
  { code: '102300', name: 'Finished Goods', type: 'asset', subType: 'Current Assets', description: 'IAS 2 – Completed goods awaiting sale.' },
  { code: '102400', name: 'Trading Stock', type: 'asset', subType: 'Current Assets', description: 'IAS 2 – Goods purchased for resale. FIFO or Weighted Average; LIFO not permitted.' },
  { code: '102500', name: 'Spare Parts & Consumables', type: 'asset', subType: 'Current Assets', description: 'IAS 2 / IAS 16 – Parts not meeting PP&E threshold. Expense when consumed.' },
  { code: '102600', name: 'Inventory Write-down (contra)', type: 'asset', subType: 'Current Assets', description: 'IAS 2 – NRV write-down below cost.' },
  { code: '103000', name: 'Financial Assets – Current', type: 'asset', subType: 'Current Assets', description: 'IFRS 9 – Current financial assets.' },
  { code: '103100', name: 'Held-for-Trading Securities', type: 'asset', subType: 'Current Assets', description: 'IFRS 9 – Equities & bonds held for short-term trading. Mark-to-market.' },
  { code: '103200', name: 'Treasury Bills (Govt.)', type: 'asset', subType: 'Current Assets', description: 'IFRS 9 – Short-dated FGN T-bills. WHT deducted at source.' },
  { code: '103300', name: 'Commercial Paper', type: 'asset', subType: 'Current Assets', description: 'IFRS 9 – Short-term debt instruments.' },
  { code: '104000', name: 'Other Current Assets', type: 'asset', subType: 'Current Assets', description: 'IAS 1 – Miscellaneous current assets.' },
  { code: '104100', name: 'Assets Classified as Held for Sale', type: 'asset', subType: 'Current Assets', description: 'IFRS 5 – Must meet IFRS 5 criteria. Measure at lower of carrying amount & FV less costs to sell.' },
  { code: '104200', name: 'Current Tax Asset', type: 'asset', subType: 'Current Assets', description: 'IAS 12 – Overpayment of CIT / EDT. Refund claim or offset against future liability.' },

  // ── NON-CURRENT ASSETS ──
  { code: '200000', name: 'Property, Plant & Equipment (PP&E)', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Tangible long-lived assets.' },
  { code: '200100', name: 'Land', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Freehold / leasehold land. Certificate of Occupancy (C of O) required in Nigeria.' },
  { code: '200200', name: 'Buildings', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Office blocks, warehouses, factories. Useful life 25–50 years.' },
  { code: '200201', name: 'Accumulated Depreciation – Buildings', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Contra-asset account.' },
  { code: '200300', name: 'Plant & Machinery', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Initial Capital Allowance 50% Yr1; Annual Allowance 25% (CITA 3rd Schedule).' },
  { code: '200301', name: 'Accumulated Depreciation – Plant & Machinery', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Contra-asset account.' },
  { code: '200400', name: 'Motor Vehicles', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Capital Allowance: Initial 50%, Annual 25%.' },
  { code: '200401', name: 'Accumulated Depreciation – Motor Vehicles', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Contra-asset account.' },
  { code: '200500', name: 'Furniture & Fittings', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Capital Allowance: Initial 25%, Annual 20%.' },
  { code: '200501', name: 'Accumulated Depreciation – Furniture & Fittings', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Contra-asset account.' },
  { code: '200600', name: 'Computer & IT Equipment', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Capital Allowance: Initial 25%, Annual 25%.' },
  { code: '200601', name: 'Accumulated Depreciation – Computer & IT Equipment', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Contra-asset account.' },
  { code: '200700', name: 'Generator & Power Equipment', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Critical due to Nigeria power infrastructure. Capital Allowance applicable.' },
  { code: '200701', name: 'Accumulated Depreciation – Generator & Power Equip.', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Contra-asset account.' },
  { code: '200800', name: 'Capital Work-in-Progress (CWIP)', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 16 – Assets under construction; not yet in use. Borrowing costs capitalised per IAS 23.' },
  { code: '201000', name: 'Right-of-Use Assets (IFRS 16)', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 16 – Leased assets recognised on balance sheet.' },
  { code: '201100', name: 'ROU – Buildings', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 16 – Right-of-use buildings.' },
  { code: '201101', name: 'Accumulated Depreciation – ROU Buildings', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 16 – Contra-asset account.' },
  { code: '201200', name: 'ROU – Motor Vehicles', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 16 – Right-of-use motor vehicles.' },
  { code: '201201', name: 'Accumulated Depreciation – ROU Vehicles', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 16 – Contra-asset account.' },
  { code: '202000', name: 'Intangible Assets', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 38 – Non-physical long-lived assets.' },
  { code: '202100', name: 'Goodwill', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 3 / IAS 36 – Arising on business combination. Not amortised; annual impairment test.' },
  { code: '202200', name: 'Software Licences', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 38 – WHT on software royalties per FIRS; amortise over useful life.' },
  { code: '202300', name: 'Patents & Trademarks', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 38 – Intangible property rights.' },
  { code: '202400', name: 'Franchise Rights', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 38 – Franchise agreements.' },
  { code: '202500', name: 'Accumulated Amortisation – Intangibles', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 38 – Contra-asset account.' },
  { code: '203000', name: 'Investment Property', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 40 – Property held for rental or capital appreciation. Fair value or cost model.' },
  { code: '204000', name: 'Investments – Non-current', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 9 / IAS 28 – Long-term investments.' },
  { code: '204100', name: 'Investment in Subsidiaries', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 10 / IAS 27 – Consolidated in group FS; cost model in separate FS.' },
  { code: '204200', name: 'Investment in Associates', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 28 – Equity method.' },
  { code: '204300', name: 'Investment in Joint Ventures', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 11 – Equity method.' },
  { code: '204400', name: 'Long-term Bonds & Debentures', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 9 – Amortised cost. WHT 10% on interest.' },
  { code: '204500', name: 'FGN & State Government Bonds', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 9 – Federal & State bonds. WHT deducted at source.' },
  { code: '205000', name: 'Deferred Tax Asset', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 12 – Recognise only when recovery probable.' },
  { code: '206000', name: 'Other Non-current Assets', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 1 – Miscellaneous non-current assets.' },
  { code: '206100', name: 'Long-term Prepayments & Deposits', type: 'asset', subType: 'Non-Current Assets', description: 'IAS 1 – Rent deposits, utility bonds.' },
  { code: '206200', name: 'Long-term Receivables', type: 'asset', subType: 'Non-Current Assets', description: 'IFRS 9 – ECL applies.' },

  // ── CURRENT LIABILITIES ──
  { code: '300000', name: 'Trade & Other Payables', type: 'liability', subType: 'Current Liabilities', description: 'IAS 1 / IFRS 9 – Obligations due within 12 months.' },
  { code: '300100', name: 'Trade Creditors / Accounts Payable', type: 'liability', subType: 'Current Liabilities', description: 'IAS 1 – Amounts owed to suppliers. Deduct WHT at applicable rate.' },
  { code: '300200', name: 'Accrued Expenses', type: 'liability', subType: 'Current Liabilities', description: 'IAS 1 / IAS 37 – Expenses incurred but not invoiced.' },
  { code: '300300', name: 'Other Payables', type: 'liability', subType: 'Current Liabilities', description: 'IAS 1 – Miscellaneous current creditors.' },
  { code: '300400', name: 'Due to Related Parties', type: 'liability', subType: 'Current Liabilities', description: 'IAS 24 – Transfer pricing — FIRS Regulations.' },
  { code: '300500', name: 'Customer Deposits & Advances', type: 'liability', subType: 'Current Liabilities', description: 'IFRS 15 – Contract liabilities; revenue recognition when performance satisfied.' },
  { code: '300600', name: 'Deferred Revenue – Current', type: 'liability', subType: 'Current Liabilities', description: 'IFRS 15 – Unearned revenue — current portion.' },
  { code: '301000', name: 'Tax Liabilities', type: 'liability', subType: 'Current Liabilities', description: 'IAS 12 / CITA – Aggregate tax obligations.' },
  { code: '301100', name: 'Company Income Tax Payable (CIT)', type: 'liability', subType: 'Current Liabilities', description: 'CITA – CIT on taxable profits. Small company: turnover ≤ ₦25m; Medium ₦25m–₦100m.' },
  { code: '301200', name: 'Education Tax Payable (EDT)', type: 'liability', subType: 'Current Liabilities', description: 'Education Tax Act – 2.5% of assessable profits. File with CIT return.' },
  { code: '301300', name: 'VAT Payable (Output VAT)', type: 'liability', subType: 'Current Liabilities', description: 'VATA – VAT collected from customers less input VAT. File monthly; due 21st.' },
  { code: '301400', name: 'WHT Payable', type: 'liability', subType: 'Current Liabilities', description: 'CITA / WHT Regs – WHT deducted from payments; remit to FIRS within 30 days.' },
  { code: '301500', name: 'PAYE Payable', type: 'liability', subType: 'Current Liabilities', description: 'PITA – Employee income tax deducted at source. Remit to State IRS by 10th.' },
  { code: '301600', name: 'Pension Contribution Payable', type: 'liability', subType: 'Current Liabilities', description: 'Pension Reform Act – 10% employer / 8% employee. Remit to PFA within 7 days.' },
  { code: '301700', name: 'NSITF Contribution Payable', type: 'liability', subType: 'Current Liabilities', description: 'NSITF Act – 1% of total monthly payroll. Remit to NSITF.' },
  { code: '301800', name: 'NHF Contribution Payable', type: 'liability', subType: 'Current Liabilities', description: 'NHF Act – 2.5% of employee salary. Remit to FMBN.' },
  { code: '301900', name: 'NITDA Levy Payable', type: 'liability', subType: 'Current Liabilities', description: 'NITDA Act – 1% of PBT for companies with turnover > ₦100m.' },
  { code: '301950', name: 'TETFund Levy Payable', type: 'liability', subType: 'Current Liabilities', description: 'TETFund Act – Tertiary Education Trust Fund levy.' },
  { code: '302000', name: 'Short-term Borrowings', type: 'liability', subType: 'Current Liabilities', description: 'IFRS 9 – Bank overdrafts, short-term loans. WHT on interest at 10%.' },
  { code: '302100', name: 'Bank Overdraft', type: 'liability', subType: 'Current Liabilities', description: 'IFRS 9 – Overdraft facility.' },
  { code: '302200', name: 'Short-term Loans', type: 'liability', subType: 'Current Liabilities', description: 'IFRS 9 – Loans due within 12 months.' },
  { code: '302300', name: 'Commercial Paper Issued', type: 'liability', subType: 'Current Liabilities', description: 'IFRS 9 – Short-term debt instruments issued.' },
  { code: '303000', name: 'Current Portion of Long-term Debt', type: 'liability', subType: 'Current Liabilities', description: 'IFRS 9 – Long-term liabilities due within 12 months.' },
  { code: '304000', name: 'Lease Liabilities – Current', type: 'liability', subType: 'Current Liabilities', description: 'IFRS 16 – Current portion of lease obligations.' },
  { code: '305000', name: 'Dividends Payable', type: 'liability', subType: 'Current Liabilities', description: 'IAS 10 / IAS 32 – Declared but unpaid dividends. WHT 10% on payment.' },

  // ── NON-CURRENT LIABILITIES ──
  { code: '400000', name: 'Long-term Borrowings', type: 'liability', subType: 'Non-Current Liabilities', description: 'IFRS 9 / IAS 32 – Long-term debt obligations.' },
  { code: '400100', name: 'Bank Loans – Long-term', type: 'liability', subType: 'Non-Current Liabilities', description: 'IFRS 9 – Effective interest rate method. WHT 10% on interest.' },
  { code: '400200', name: 'Bonds & Debentures Issued', type: 'liability', subType: 'Non-Current Liabilities', description: 'IFRS 9 / IAS 32 – Corporate bonds and debentures.' },
  { code: '400300', name: 'CBN Intervention Loans', type: 'liability', subType: 'Non-Current Liabilities', description: 'IFRS 9 – AGSMEIS, MSME loans. CBN-supported facilities.' },
  { code: '400400', name: 'Development Finance Loans', type: 'liability', subType: 'Non-Current Liabilities', description: 'IFRS 9 – BOI, NEXIM, DBN loans.' },
  { code: '401000', name: 'Lease Liabilities – Non-current', type: 'liability', subType: 'Non-Current Liabilities', description: 'IFRS 16 – Long-term lease obligations. Discount at incremental borrowing rate.' },
  { code: '402000', name: 'Deferred Tax Liability', type: 'liability', subType: 'Non-Current Liabilities', description: 'IAS 12 – Deferred tax obligations.' },
  { code: '403000', name: 'Employee Benefit Obligations', type: 'liability', subType: 'Non-Current Liabilities', description: 'IAS 19 – Long-term employee benefits.' },
  { code: '403100', name: 'Defined Benefit Pension Obligation', type: 'liability', subType: 'Non-Current Liabilities', description: 'IAS 19 – Actuarial valuation required.' },
  { code: '403200', name: 'Long Service Award Provision', type: 'liability', subType: 'Non-Current Liabilities', description: 'IAS 19 – Common in Nigerian companies.' },
  { code: '403300', name: 'Gratuity Payable', type: 'liability', subType: 'Non-Current Liabilities', description: 'IAS 19 – Terminal benefits for qualifying employees.' },
  { code: '404000', name: 'Provisions & Contingent Liabilities', type: 'liability', subType: 'Non-Current Liabilities', description: 'IAS 37 – General provisions.' },
  { code: '404100', name: 'Asset Decommissioning Provision', type: 'liability', subType: 'Non-Current Liabilities', description: 'IAS 37 – Oil & gas, mining, telecoms sectors.' },
  { code: '404200', name: 'Legal Claims Provision', type: 'liability', subType: 'Non-Current Liabilities', description: 'IAS 37 – Provision for legal disputes.' },
  { code: '404300', name: 'Warranty Provision', type: 'liability', subType: 'Non-Current Liabilities', description: 'IAS 37 – Product warranty obligations.' },
  { code: '405000', name: 'Deferred Revenue – Non-current', type: 'liability', subType: 'Non-Current Liabilities', description: 'IFRS 15 – Long-term contract liabilities.' },

  // ── EQUITY ──
  { code: '500000', name: 'Share Capital', type: 'equity', subType: 'Equity', description: 'IAS 1 / CAMA 2020 – Issued and fully paid share capital.' },
  { code: '500100', name: 'Ordinary Share Capital', type: 'equity', subType: 'Equity', description: 'IAS 1 – ₦1 or ₦0.50 par value typical in Nigeria.' },
  { code: '500200', name: 'Preference Share Capital', type: 'equity', subType: 'Equity', description: 'IAS 32 – Classify as equity or liability based on terms.' },
  { code: '501000', name: 'Share Premium', type: 'equity', subType: 'Equity', description: 'IAS 1 – Excess of issue price over par value.' },
  { code: '502000', name: 'Retained Earnings', type: 'equity', subType: 'Equity', description: 'IAS 1 – Accumulated profits net of dividends.' },
  { code: '502100', name: 'Retained Earnings – Opening', type: 'equity', subType: 'Equity', description: 'IAS 1 – Opening balance of retained earnings.' },
  { code: '502200', name: 'Profit / (Loss) for the Year', type: 'equity', subType: 'Equity', description: 'IAS 1 – Transfer from P&L at year end.' },
  { code: '502300', name: 'Dividends Declared', type: 'equity', subType: 'Equity', description: 'IAS 1 / IAS 10 – WHT 10% withheld on dividends.' },
  { code: '503000', name: 'Other Reserves', type: 'equity', subType: 'Equity', description: 'IAS 1 – Statutory and discretionary reserves.' },
  { code: '503100', name: 'Statutory Reserve', type: 'equity', subType: 'Equity', description: 'CBN Prudential Guidelines – Banks: minimum 25% of PBT.' },
  { code: '503200', name: 'Capital Redemption Reserve', type: 'equity', subType: 'Equity', description: 'CAMA 2020 – For redemption of redeemable shares.' },
  { code: '503300', name: 'Foreign Currency Translation Reserve', type: 'equity', subType: 'Equity', description: 'IAS 21 – OCI — fx translation differences on foreign operations.' },
  { code: '503400', name: 'Revaluation Surplus', type: 'equity', subType: 'Equity', description: 'IAS 16 / IAS 40 – PP&E / Investment Property revaluation gains. Not distributable.' },
  { code: '503500', name: 'Fair Value Reserve (OCI)', type: 'equity', subType: 'Equity', description: 'IFRS 9 – FVOCI financial instruments.' },
  { code: '503600', name: 'Actuarial Gains/Losses Reserve', type: 'equity', subType: 'Equity', description: 'IAS 19 – OCI — remeasurement of defined benefit obligations.' },
  { code: '504000', name: 'Non-controlling Interest', type: 'equity', subType: 'Equity', description: 'IFRS 10 – Minority interest in subsidiaries (groups only).' },
  { code: '505000', name: 'General Reserve', type: 'equity', subType: 'Equity', description: 'IAS 1 – Discretionary reserve.' },

  // ── REVENUE ──
  { code: '600000', name: 'Revenue from Contracts with Customers', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 15 – Core operating revenue. Apply 5-step model.' },
  { code: '600100', name: 'Sales of Goods', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 15 – VAT at 7.5% on taxable supplies.' },
  { code: '600200', name: 'Services Revenue', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 15 – Professional, consulting, IT, logistics. WHT deductible by customers.' },
  { code: '600300', name: 'Construction Contract Revenue', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 15 – Percentage of completion method.' },
  { code: '600400', name: 'Franchise & Licensing Revenue', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 15 – Royalties, licences. WHT 10% deducted by payer.' },
  { code: '600500', name: 'Subscription & Retainer Revenue', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 15 – Deferred until period of service.' },
  { code: '600600', name: 'Agency & Commission Income', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 15 – Recognise net commission only if agent.' },
  { code: '600700', name: 'Export Revenue', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 15 – VAT 0% zero-rated. Eligible for NEPZA incentives.' },
  { code: '600800', name: 'Agricultural Revenue', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 15 / IAS 41 – Farm produce, livestock. VAT exempt per VATA.' },
  { code: '601000', name: 'Other Operating Income', type: 'revenue', subType: 'Operating Revenue', description: 'IAS 1 – Miscellaneous operating income.' },
  { code: '601100', name: 'Rental Income', type: 'revenue', subType: 'Operating Revenue', description: 'IAS 40 / IFRS 16 – WHT 10% deducted by corporate tenants.' },
  { code: '601200', name: 'Dividend Income', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 9 / IAS 28 – WHT 10% deducted at source.' },
  { code: '601300', name: 'Interest Income', type: 'revenue', subType: 'Operating Revenue', description: 'IFRS 9 – WHT 10% deducted at source; claim credit.' },
  { code: '601400', name: 'Profit on Disposal of Assets', type: 'revenue', subType: 'Operating Revenue', description: 'IAS 16 – Gain on sale of PP&E. Taxable in hands of company.' },
  { code: '601500', name: 'Scrap & Waste Sales', type: 'revenue', subType: 'Operating Revenue', description: 'IAS 2 – Proceeds from scrap sales.' },
  { code: '601600', name: 'Grant Income', type: 'revenue', subType: 'Operating Revenue', description: 'IAS 20 – Government grants & subsidies.' },
  { code: '601700', name: 'Insurance Claims Received', type: 'revenue', subType: 'Operating Revenue', description: 'IAS 1 – Insurance proceeds.' },
  { code: '601800', name: 'Exchange Gains – Operating', type: 'revenue', subType: 'Operating Revenue', description: 'IAS 21 – Fx gains on operating transactions. Taxable.' },

  // ── COST OF SALES ──
  { code: '700000', name: 'Cost of Sales', type: 'expense', subType: 'Cost of Sales', description: 'IAS 2 – Direct costs of goods sold.' },
  { code: '700100', name: 'Opening Stock', type: 'expense', subType: 'Cost of Sales', description: 'IAS 2 – Opening inventory value.' },
  { code: '700200', name: 'Purchases of Goods', type: 'expense', subType: 'Cost of Sales', description: 'IAS 2 – VAT input where applicable; include import duties.' },
  { code: '700300', name: 'Import Duties & Levies', type: 'expense', subType: 'Cost of Sales', description: 'IAS 2 / Customs Act – Nigeria Customs Service charges.' },
  { code: '700400', name: 'Direct Labour – Manufacturing', type: 'expense', subType: 'Cost of Sales', description: 'IAS 2 – Direct manufacturing labour.' },
  { code: '700500', name: 'Direct Overheads – Manufacturing', type: 'expense', subType: 'Cost of Sales', description: 'IAS 2 – Factory rent, utilities, maintenance.' },
  { code: '700600', name: 'Closing Stock (contra)', type: 'expense', subType: 'Cost of Sales', description: 'IAS 2 – Deducted to derive COGS. Lower of cost and NRV.' },
  { code: '700700', name: 'Cost of Services Delivered', type: 'expense', subType: 'Cost of Sales', description: 'IFRS 15 – Staff costs & direct costs for service projects.' },
  { code: '700800', name: 'Agricultural / Production Costs', type: 'expense', subType: 'Cost of Sales', description: 'IAS 41 / IAS 2 – Farming inputs, feeds, fertilisers.' },

  // ── STAFF COSTS ──
  { code: '800000', name: 'Salaries & Wages', type: 'expense', subType: 'Staff Costs', description: 'IAS 19 – Gross employee remuneration. PAYE at graduated rates.' },
  { code: '800100', name: 'Employer Pension Contribution', type: 'expense', subType: 'Staff Costs', description: 'Pension Reform Act – 10% of employee monthly emolument. Remit to PFA within 7 days.' },
  { code: '800200', name: 'NSITF Contribution', type: 'expense', subType: 'Staff Costs', description: 'NSITF Act – 1% of total monthly payroll. Remit monthly to NSITF.' },
  { code: '800300', name: 'NHF Employer Contribution', type: 'expense', subType: 'Staff Costs', description: 'NHF Act – 2.5% of employee salary.' },
  { code: '800400', name: 'Staff Medical Expenses', type: 'expense', subType: 'Staff Costs', description: 'IAS 19 – HMO, clinic bills. Taxable benefit if personal.' },
  { code: '800500', name: 'Staff Training & Development', type: 'expense', subType: 'Staff Costs', description: 'IAS 19 – Professional development, ICAN, ANAN, CITN CPD.' },
  { code: '800600', name: 'Leave Allowance', type: 'expense', subType: 'Staff Costs', description: 'PITA – Annual leave pay as required by law.' },
  { code: '800700', name: '13th Month & Bonuses', type: 'expense', subType: 'Staff Costs', description: 'PITA – Taxable; disclose separately.' },
  { code: '800800', name: 'Redundancy & Severance Costs', type: 'expense', subType: 'Staff Costs', description: 'IAS 19 / Labour Act – Labour Act 2004 requirements.' },
  { code: '800900', name: 'Gratuity Expense', type: 'expense', subType: 'Staff Costs', description: 'IAS 19 – Service award, long-service costs.' },

  // ── ADMINISTRATIVE EXPENSES ──
  { code: '810000', name: 'Office Rent & Rates', type: 'expense', subType: 'Administrative Expenses', description: 'IFRS 16 – WHT 10% deducted by corporate payers on rent.' },
  { code: '810100', name: 'Utilities – Electricity (DISCO/Generator)', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – PHCN/DISCO bills plus diesel.' },
  { code: '810200', name: 'Diesel & Fuel for Generator', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – Common operating cost given epileptic power supply.' },
  { code: '810300', name: 'Water Bills & Sewage', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – Utility expenses.' },
  { code: '810400', name: 'Office Supplies & Stationery', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – Consumable office supplies.' },
  { code: '810500', name: 'Postage & Courier', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – Postage and courier services.' },
  { code: '810600', name: 'Insurance – General', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 / NAICOM Regs – Motor, office, public liability.' },
  { code: '810700', name: 'Depreciation – PP&E', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 16 – Non-cash; charged to P&L.' },
  { code: '810800', name: 'Amortisation – Intangibles', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 38 – Amortisation of intangible assets.' },
  { code: '810900', name: 'Depreciation – ROU Assets', type: 'expense', subType: 'Administrative Expenses', description: 'IFRS 16 – Depreciation of right-of-use assets.' },
  { code: '811000', name: 'CAC Annual Returns Filing Fees', type: 'expense', subType: 'Administrative Expenses', description: 'CAMA 2020 – Annual compliance cost.' },
  { code: '811100', name: 'FIRS & Tax Compliance Costs', type: 'expense', subType: 'Administrative Expenses', description: 'CITA / VATA / PITA – Tax returns preparation costs.' },
  { code: '811200', name: 'Legal & Professional Fees', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – WHT 10% deducted when paying bodies corporate.' },
  { code: '811300', name: 'Audit Fees', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 / CAMA – Mandatory audit for companies. WHT 10%.' },
  { code: '811400', name: 'Bank Charges & Commissions', type: 'expense', subType: 'Administrative Expenses', description: 'IFRS 9 – Service charges, transfer fees, COT.' },
  { code: '811500', name: 'Subscription & Membership Dues', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – Professional bodies, trade associations.' },
  { code: '811600', name: 'Vehicle Running Expenses', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – Fuel, maintenance, registration. VIO, FRSC compliance.' },
  { code: '811700', name: 'Repairs & Maintenance', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 / IAS 16 – Capitalise if extends asset life; expense if routine.' },
  { code: '811800', name: 'Security Costs', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – Guards, surveillance, armoured vans.' },
  { code: '811900', name: 'Cleaning & Janitorial Services', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – WHT on payments to companies.' },
  { code: '812000', name: 'Printing & Reproduction', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 – Printing and document services.' },
  { code: '812100', name: 'IT & Software Expenses', type: 'expense', subType: 'Administrative Expenses', description: 'IAS 1 / IAS 38 – SaaS, maintenance, software support.' },

  // ── SELLING & DISTRIBUTION ──
  { code: '820000', name: 'Advertising & Marketing', type: 'expense', subType: 'Selling & Distribution', description: 'IAS 1 – WHT 10% on agency fees; VAT on media spend.' },
  { code: '820100', name: 'Sales Commission', type: 'expense', subType: 'Selling & Distribution', description: 'IFRS 15 – WHT on commissions paid to entities; PAYE if individual.' },
  { code: '820200', name: 'Freight & Delivery Costs', type: 'expense', subType: 'Selling & Distribution', description: 'IAS 1 – Outbound logistics.' },
  { code: '820300', name: 'Market Research', type: 'expense', subType: 'Selling & Distribution', description: 'IAS 1 – Research and analysis costs.' },
  { code: '820400', name: 'Sponsorship & Promotions', type: 'expense', subType: 'Selling & Distribution', description: 'IAS 1 – Deductible if wholly for business purposes.' },
  { code: '820500', name: 'Export Expenses & Documentation', type: 'expense', subType: 'Selling & Distribution', description: 'IAS 1 / NEPC – NXP forms, shipping, freight.' },
  { code: '820600', name: 'Distributor & Channel Incentives', type: 'expense', subType: 'Selling & Distribution', description: 'IFRS 15 – Channel partner incentives.' },

  // ── OTHER OPERATING EXPENSES ──
  { code: '830000', name: 'Impairment Loss – Receivables', type: 'expense', subType: 'Other Operating Expenses', description: 'IFRS 9 – ECL charge. Tax deductible only when written off per CITA.' },
  { code: '830100', name: 'Impairment Loss – Non-Financial Assets', type: 'expense', subType: 'Other Operating Expenses', description: 'IAS 36 – CGU impairment testing.' },
  { code: '830200', name: 'Provision for Onerous Contracts', type: 'expense', subType: 'Other Operating Expenses', description: 'IAS 37 – Onerous contract provisions.' },
  { code: '830300', name: 'Foreign Exchange Losses', type: 'expense', subType: 'Other Operating Expenses', description: 'IAS 21 – Fx losses on operating transactions. Deductible if realised.' },
  { code: '830400', name: 'Donations & CSR Expenses', type: 'expense', subType: 'Other Operating Expenses', description: 'IAS 1 / Finance Act – Tax deductible up to 10% of assessable profit.' },
  { code: '830500', name: 'Penalties & Fines', type: 'expense', subType: 'Other Operating Expenses', description: 'IAS 37 – NOT tax deductible — disallowed per CITA.' },
  { code: '830600', name: 'Losses on Disposal of Assets', type: 'expense', subType: 'Other Operating Expenses', description: 'IAS 16 – Loss on sale of PP&E.' },

  // ── FINANCE INCOME ──
  { code: '900000', name: 'Finance Income', type: 'revenue', subType: 'Finance Income', description: 'IFRS 9 – Interest and investment income.' },
  { code: '900100', name: 'Interest Income on Deposits', type: 'revenue', subType: 'Finance Income', description: 'IFRS 9 – WHT deducted by bank.' },
  { code: '900200', name: 'Interest Income on Loans', type: 'revenue', subType: 'Finance Income', description: 'IFRS 9 – Effective interest rate method.' },
  { code: '900300', name: 'Dividend Income (investment)', type: 'revenue', subType: 'Finance Income', description: 'IFRS 9 – Tax-exempt from Nigerian resident companies.' },
  { code: '900400', name: 'Foreign Exchange Gains – Financing', type: 'revenue', subType: 'Finance Income', description: 'IAS 21 – Fx gains on financing activities.' },

  // ── FINANCE COSTS ──
  { code: '910000', name: 'Finance Costs', type: 'expense', subType: 'Finance Costs', description: 'IFRS 9 / IAS 23 – Interest and borrowing costs.' },
  { code: '910100', name: 'Interest Expense – Bank Loans', type: 'expense', subType: 'Finance Costs', description: 'IFRS 9 – WHT 10% on interest paid to financial institutions.' },
  { code: '910200', name: 'Interest Expense – Bonds', type: 'expense', subType: 'Finance Costs', description: 'IFRS 9 – Bond interest expense.' },
  { code: '910300', name: 'Interest Expense – Lease Liabilities', type: 'expense', subType: 'Finance Costs', description: 'IFRS 16 – Unwinding of lease discount.' },
  { code: '910400', name: 'Borrowing Costs Capitalised', type: 'expense', subType: 'Finance Costs', description: 'IAS 23 – Capitalised to CWIP.' },
  { code: '910500', name: 'Bank Charges – Financing', type: 'expense', subType: 'Finance Costs', description: 'IFRS 9 – Arrangement fees, early repayment charges.' },
  { code: '910600', name: 'Foreign Exchange Losses – Financing', type: 'expense', subType: 'Finance Costs', description: 'IAS 21 – Fx losses on foreign currency borrowings.' },

  // ── TAX EXPENSE ──
  { code: '950000', name: 'Income Tax Expense', type: 'expense', subType: 'Tax Expense', description: 'IAS 12 / CITA – Aggregate income tax charge.' },
  { code: '950100', name: 'Current Tax – CIT', type: 'expense', subType: 'Tax Expense', description: 'CITA – Company Income Tax charge. 30% / 20% / 0% bands.' },
  { code: '950200', name: 'Education Tax (EDT)', type: 'expense', subType: 'Tax Expense', description: 'Education Tax Act – 2.5% of assessable profit.' },
  { code: '950300', name: 'Deferred Tax (Charge) / Credit', type: 'expense', subType: 'Tax Expense', description: 'IAS 12 – Deferred tax movement.' },
  { code: '950400', name: 'Capital Gains Tax', type: 'expense', subType: 'Tax Expense', description: 'CGTA – 10% on chargeable gains.' },
  { code: '950500', name: 'Petroleum Profits Tax (if applicable)', type: 'expense', subType: 'Tax Expense', description: 'PPTA – For upstream oil & gas companies. 50–85%.' },

];

export async function seedAccounts(orgId: string) {
  const existing = await db.select({ id: accounts.id }).from(accounts).where(eq(accounts.orgId, orgId)).limit(1);
  if (existing.length > 0) {
    return { seeded: 0, message: 'Accounts already exist for this organisation.' };
  }
  const values = ACCOUNT_SEEDS.map(a => ({
    ...a,
    orgId,
    isSystem: true,
    isActive: true,
  }));
  await db.insert(accounts).values(values);
  return { seeded: values.length, message: `Seeded ${values.length} accounts.` };
}

export default ACCOUNT_SEEDS;
