import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { reportsApi } from '../../lib/api';
import { Loader2, Save, RefreshCw, Plus, FileText, Eye, Pencil } from 'lucide-react';

interface Note {
  id: string;
  noteNumber: string;
  title: string;
  content: string | null;
  autoGenerated: boolean;
  sourceReport: string | null;
  sortOrder: number;
}

export function NotesPage() {
  const queryClient = useQueryClient();
  const [sourceReport, setSourceReport] = useState<string>('');
  const [editingNote, setEditingNote] = useState<Note | null>(null);
  const [editContent, setEditContent] = useState('');
  const [showRaw, setShowRaw] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ['financial-notes', sourceReport],
    queryFn: async () => {
      const res = await reportsApi.getNotes(sourceReport ? { sourceReport } : {});
      return res.data || [];
    },
  });

  const notes: Note[] = Array.isArray(data) ? data : [];

  const generateMutation = useMutation({
    mutationFn: async () => {
      const res = await reportsApi.generateNotes({ reportDate: new Date().toISOString().split('T')[0] });
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['financial-notes'] });
    },
  });

  const updateMutation = useMutation({
    mutationFn: async ({ id, content }: { id: string; content: string }) => {
      const note = notes.find(n => n.id === id);
      if (!note) return;
      const res = await reportsApi.updateNote(id, {
        noteNumber: note.noteNumber,
        title: note.title,
        content,
        autoGenerated: false,
        sortOrder: note.sortOrder,
        sourceReport: note.sourceReport || undefined,
      });
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['financial-notes'] });
      setEditingNote(null);
    },
  });

  const sourceReports = [
    { value: '', label: 'All Notes' },
    { value: 'annual_report', label: 'Annual Report' },
    { value: 'income_statement', label: 'Income Statement' },
    { value: 'balance_sheet', label: 'Balance Sheet' },
    { value: 'cash_flow', label: 'Cash Flow' },
  ];

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      <div className="flex items-center justify-between">

        <div className="flex gap-2">
          <select
            value={sourceReport}
            onChange={(e) => setSourceReport(e.target.value)}
            className="border border-slate-300 rounded-lg px-3 py-2 text-sm"
          >
            {sourceReports.map(sr => (
              <option key={sr.value} value={sr.value}>{sr.label}</option>
            ))}
          </select>
          <button
            onClick={() => generateMutation.mutate()}
            disabled={generateMutation.isPending}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 text-sm"
          >
            <RefreshCw className="w-4 h-4" />
            Generate Notes
          </button>
          <button
            onClick={() => setShowRaw(!showRaw)}
            className="flex items-center gap-2 px-4 py-2 border border-slate-300 rounded-lg hover:bg-slate-50 text-sm"
          >
            <Eye className="w-4 h-4" />
            {showRaw ? 'Formatted' : 'Raw'}
          </button>
        </div>
      </div>

      {generateMutation.isPending && (
        <div className="flex items-center gap-2 text-indigo-600 bg-indigo-50 rounded-lg p-4">
          <Loader2 className="w-4 h-4 animate-spin" />
          Generating IFRS disclosure notes from financial data...
        </div>
      )}

      {isLoading ? (
        <div className="flex justify-center py-12">
          <Loader2 className="w-8 h-8 animate-spin text-slate-400" />
        </div>
      ) : notes.length === 0 ? (
        <div className="text-center py-12 text-slate-500">
          <FileText className="w-12 h-12 mx-auto mb-3 text-slate-300" />
          <p className="text-lg font-medium">No notes generated yet</p>
          <p className="text-sm mt-1">Click "Generate Notes" to auto-create IFRS disclosure notes from your financial data.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {notes
            .sort((a, b) => parseInt(a.noteNumber) - parseInt(b.noteNumber))
            .map((note) => (
              <div key={note.id} className="bg-white rounded-lg border border-slate-200 overflow-hidden">
                <div className="flex items-start justify-between p-4 border-b border-slate-100 bg-slate-50">
                  <div>
                    <h3 className="font-semibold text-slate-900 text-sm">
                      Note {note.noteNumber}: {note.title}
                    </h3>
                    <span className="text-xs text-slate-500">
                      {note.sourceReport || 'General'} &middot; {note.autoGenerated ? 'Auto-generated' : 'Custom'}
                    </span>
                  </div>
                  <button
                    onClick={() => {
                      setEditingNote(note);
                      setEditContent(note.content || '');
                    }}
                    className="p-1.5 rounded hover:bg-slate-200 text-slate-500"
                  >
                    <Pencil className="w-4 h-4" />
                  </button>
                </div>
                <div className="p-4">
                  {editingNote?.id === note.id ? (
                    <div className="space-y-2">
                      <textarea
                        value={editContent}
                        onChange={(e) => setEditContent(e.target.value)}
                        className="w-full border border-slate-300 rounded-lg p-3 text-sm min-h-[150px]"
                      />
                      <div className="flex gap-2 justify-end">
                        <button
                          onClick={() => setEditingNote(null)}
                          className="px-3 py-1.5 text-sm border border-slate-300 rounded-lg hover:bg-slate-50"
                        >
                          Cancel
                        </button>
                        <button
                          onClick={() => updateMutation.mutate({ id: note.id, content: editContent })}
                          disabled={updateMutation.isPending}
                          className="flex items-center gap-1 px-3 py-1.5 text-sm bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50"
                        >
                          <Save className="w-3.5 h-3.5" />
                          Save
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">
                      {showRaw ? (
                        <pre className="font-mono text-xs bg-slate-50 p-3 rounded overflow-x-auto">{note.content || ''}</pre>
                      ) : (
                        (note.content || '').split('\n').map((line, i) => (
                          <p key={i} className="mb-1">{line || '\u00A0'}</p>
                        ))
                      )}
                    </div>
                  )}
                </div>
              </div>
            ))}
        </div>
      )}
    </div>
  );
}
